title: # a name for your Learning Lab coursep
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: template-repo
  repo: FifiTeklemedhin/template-repo

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: respond
  with: 01_first-response.md
# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: What makes a good research question? 
- title:  What makes a good research question? 
  description: # a description of the step, shown to the learner in the course progress page
  event: issue_commented.created
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: gate
    left: '%payload.pull_request.title%'
    operator: ===
    right: Add name to README

# Step 2: How do you write your own question?
- title: How do you write your own question?
  description: # a description of the step, shown to the learner in the course progress page
  event: issue_commented.created
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: What does good data look like?
- title: What does good data look like?
  description: # a description of the step, shown to the learner in the course progress page
  event: issues.closed
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: How do you search for good data?
- title: How do you search for good data?
  description: # a description of the step, shown to the learner in the course progress page
  event: issue_commented.created
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: How do you use that data?
- title: How do you use that data?
  description: # a description of the step, shown to the learner in the course progress page
  event: issues.closed
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions
